version: 0.2
    
phases:
  install:
    commands:
      - sudo yum -y install curl
      - curl -sL https://rpm.nodesource.com/setup_16.x | sudo bash -
      - sudo yum install -y nodejs
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - 'out/**/*'
  discard-paths: no

