version: 0.2
    
phases:
  install:
    commands:
      - echo "installing curl"
      - sudo yum -y install curl
      - echo "getting node"
      - sudo curl --silent --location https://rpm.nodesource.com/setup_14.x | bash -
      - echo "installing node"
      - sudo yum install -y nodejs
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - 'out/**/*'
  discard-paths: no

